chore(storybook): update storybook to latest
Because:

* Latest update to Next.js requires latest version of storybook packages
  to resolve `Error: Cannot find module
  'next/dist/shared/lib/router-context'`

This commit:

* Updates storybook packages to latest

Closes #